Module3 task1
htmlacademy-react/1618361-six-cities-5 pull request #8
Opened 2020-10-12 06:50 UTC by Cestrus

Сделал компоненты (больше чем требовалось в задании, некоторые наперёд). Поскольку число компонентов увеличилось, стало сложнее в них разобраться, т.к. свалены в одну папку components. В связи с этим есть желание сделать папки страниц и разнести компоненты постранично. Делать этого не стал из-за боязни выйти за рамки установленных условий задания.

2020-10-12 08:20 UTC, AKolodeev requested changes
Алексей, привет! Есть несколько довольно значительных багов (когда делаешь присваивание из props в конструкторе). Сейчас ты их не наблюдаешь по причине того, что props у нас не динамические - они берутся один раз из моков.

Также, ты, случаем, с Angular никогда не работал? Ты используешь именования файлов почти как принято там, в то время как в Реакт принято использовать такое же имя, как у компонента. Например, если твой компонент называется `OfferList`, то файл с ним должен называться `OfferList.js` - поправь по всему приложению. Знаю, это боль, но нужно сделать :\

Так же, рекомендую не делать изменений наперед, если это не обусловленно чем-то серьезным. Это и мне мешает ревьюить, и тебе потом может понадобиться менять код, на который ты уже потратил время.

2020-10-12 08:20 UTC, AKolodeev commented on src/components/favorites-list/favorites-list.jsx
> +      for (let j = 0; j < offers.length; j++) {
Обычно, в приложениях написанных на React не используются императивные `for`. Поэтому предлагаю сделать два изменения:
1. Использовать объект: по ключу (например, "Paris") хранить офферы с `isFavorites === true`;
2. Использовать более декларативный подход с помощью `reduce`.

Я хочу, чтобы ты сам написал решение, но приведу пример. Допустим, у нас есть массив домашних работ `homeworks`, у каждой их которых есть оценка (от 1 до 5) и предмет ("Математика", "Программирование", ...). Мы хотим сгруппировать домашние работы по оценке, где предмет домашней работы - "Программирование". Вот так я бы написал решение:
```javascript
const homeworksByMark = homeworks.reduce(
  (result, homework) =>{
    result[homework.mark] = result[homework.mark] || [];
    
    if (homework.subject === "Программирование") {
      result[homework.mark].push(homework);
    }

    return result;
  },
  {},
);
```

Далее мы можем использовать например `Object.values`, чтобы получить значения (массивы домашних работ) и что-то с ними сделать.

2020-10-12 08:20 UTC, AKolodeev commented on src/components/favorites-list/favorites-list.jsx
> +      for (let j = 0; j < offers.length; j++) {
[Вот тут](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) можно познакомиться с `reduce` (можешь посмотреть еще и `filter`)

2020-10-12 08:20 UTC, AKolodeev commented on src/components/favorites-list/favorites-list.jsx
> +            key={index}
По хорошему, было бы лучше использовать название города в качестве ключа (см. мой пример с reduce)

2020-10-12 08:20 UTC, AKolodeev commented on src/components/form-login/form-login.jsx
> +    this.user = props.user;
Что произойдет, если нам придет новый `user` из `props`?

2020-10-12 08:20 UTC, AKolodeev commented on src/components/form-send-comment/form-send-comment.jsx
> +  handleSubmit(ev) {
В Реакт принято именовать `event` как `event` или просто `e` (я предпочитаю первый вариант). Лучше придерживать best practises :)

2020-10-12 08:20 UTC, AKolodeev commented on src/components/form-send-comment/star-line/star-line.jsx
> +  const rating = [{title: `perfect`, value: 5}, {title: `good`, value: 4}, {title: `not bad`, value: 3}, {title: `badly`, value: 2}, {title: `terribly`, value: 1}];
Круто, что сделал, давай только доведем до конца :) Первые три `title` у тебя - это прилагательные (adjective) и тут все ОК, а последние два - наречия (adverb), что не совсем корректно. Должно быть `bad` и `terrible` :)

2020-10-12 08:20 UTC, AKolodeev commented on src/components/form-send-comment/star-line/star-line.jsx
> +            key={index}
`index` рекомендуется использовать только в крайнем случае, когда другого варианта нет. У тебя есть даже два варианта - либо `title`, либо `value` - используй любой на твое усмотрение.

2020-10-12 08:20 UTC, AKolodeev commented on src/components/inside-item-list/inside-item-list.jsx
> +            key={index}
Используй сам `item` в качестве ключа.

2020-10-12 09:54 UTC, Cestrus commented
Приветствую, Александр! Спасибо за подробные комментарии к коду с примерами! Начинаю исправлять. Есть момент с именованием файлов. Согласно критерия [Б36]( https://up.htmlacademy.ru/react/5/criteries#b36 ) в проекте имена файлов именуются в kebab-style, если я всё правильно понял, что странно, т.к. действительно должен быть camelStyle. Но не проблема, исправлю :)

2020-10-12 16:12 UTC, AKolodeev commented
> Приветствую, Александр! Спасибо за подробные комментарии к коду с примерами! Начинаю исправлять. Есть момент с именованием файлов. Согласно критерия [Б36](https://up.htmlacademy.ru/react/5/criteries#b36) в проекте имена файлов именуются в kebab-style, если я всё правильно понял, что странно, т.к. действительно должен быть camelStyle. Но не проблема, исправлю :)

Блин, точно, спасибо. Я не доглядел :/ Давай тогда оставим именование как ты сделал.

2020-10-13 13:44 UTC, Cestrus commented on src/components/favorites-list/favorites-list.jsx
> +  (function () {
Исходил из следующего.
в пропсах приходит массив квартир. На странице необходимо выводить избранные квартиры с разбивкой по городам, т.е. нужен массив, состоящий из массивов квартир уже сортированных по городам. Эта функция делает эту сортировку. И ее нужно как-то автоматически вызывать внутри компонента после получения данных, а компонент функциональный и в конструктор или жизненный цикл ее не воткнешь. Была идея вынести ее в отдельный модуль и подключать. Как-то так :). Если перемудрил, то перепишу. :)

2020-10-13 16:38 UTC, AKolodeev commented on src/components/favorites-list/favorites-list.jsx
> +  (function () {
Компонент функциональный - ты прав, но при изменении пропсов, будет происходить и перевычисление всего, что идет до `return` (да возвращаемое значение тоже перевычисляется). То есть ты мог бы оставить только содержимое самовызывающейся функции и оно бы вычислилось тоже.

2020-10-15 07:47 UTC, AKolodeev reviewed
Алексей, привет! Все хорошо, оставил пару комментариев, над которыми было бы неплохо поработать в следующих задачах. Если есть вопросы - пиши или давай созвонимся.

2020-10-15 07:47 UTC, AKolodeev commented on src/components/app/app.jsx
> +        <Route path='/login' exact render={() => (
Можно убрать `render` и использовать просто
```javascript
<Route ...>
  <Login user={user} />
</Route>
```
Работает также, но писать легче.

2020-10-15 07:47 UTC, AKolodeev commented on src/components/app/app.jsx
> +  reviews: PropTypes.array.isRequired,
Было бы неплохо для `review` тоже создать prop type :)

2020-10-15 07:47 UTC, AKolodeev commented on src/components/favorites-list/favorites-list.jsx
> +  const offersByCities = offers.reduce((result, offer) => {
👍

2020-10-15 07:47 UTC, AKolodeev commented on src/components/favorites-list/favorites-list.jsx
> +      {Object.entries(offersByCities).map((offersByCity) => {
Молодец! Можно сделать еще чуть читаемей:
```javascript
.map([city, offers] => ...)
```

2020-10-15 07:47 UTC, AKolodeev commented on src/components/favorites-location-list/favorites-location-list.jsx
> +  offersByCity: PropTypes.array.isRequired,
Я бы разбил на два пропса: `city: PropTypes.string.isRequired` и `offers: PropTypes.arrayOf(OfferPropType).isRequired`.

2020-10-15 07:47 UTC, AKolodeev commented on src/components/inside-item-list/inside-item-list.jsx
> +// import PropTypes from 'prop-types';
Лучше удалять неиспользуемые переменные и импорты.

2020-10-15 07:47 UTC, AKolodeev commented on src/components/place-card-list/place-card-list.jsx
> +    if (offer !== oldChosenRoom) {
👍

2020-10-15 07:47 UTC, merged

2020-10-15 11:14 UTC, Cestrus commented on src/components/app/app.jsx
> +  reviews: PropTypes.array.isRequired,
Сделаю. Забавно то, что делал эти propTypes, но потом удалил