have done Leaflet Map
htmlacademy-react/1618361-six-cities-5 pull request #9
Opened 2020-10-16 15:49 UTC by Cestrus

2020-10-18 09:26 UTC, AKolodeev requested changes
Привет! Все круто, есть только вопросы по загрузке css. Также, не совсем уверен, что react-leaflet можно использовать на курсе. Задал этот вопрос, где-то в понедельник вернусь с ответом.

2020-10-18 09:26 UTC, AKolodeev commented on public/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
Привет! А почему ты решил делать так, а не через `import ' из JavaScript кода?

2020-10-18 09:26 UTC, AKolodeev commented on webpack.config.js
> +            },
Не хватает правила для загрузки css модулей.

2020-10-19 11:48 UTC, Cestrus commented
Убрал react-leaflet, переделал с использованием leaflet

2020-10-21 07:16 UTC, AKolodeev requested changes
Алексей, привет! Я проверил задание вручную (на твоей ветке) и проект не собрался. Проверяй, пожалуйста, как он работает (собирается ли + работают ли фичи) перед каждой отправкой на проверку. Если мы мержим что-то в мастер, то подразумевается, что оно работает.

Почему проект не билдился? Если ты собирешь его и посмотришь логи, то там будут ошибки, о том, что что-то не так с `.png` файлами. Давай подумаем логически. Чем мы собираем проект? С помощью чего мы преобразуем современный JS в ES5-код? Что нам позволяет импортировать CSS-стили прямо из JS?

Если не получится разобраться, то посмотри дифф в файле, который я прикрепил к этому комментарию.
[changes.txt](https://github.com/htmlacademy-react/1618361-six-cities-5/files/5413952/changes.txt)

2020-10-21 07:16 UTC, AKolodeev commented on src/components/leaflet-map/leaflet-map.jsx
> +
Делай `import 'leatlet/dist/leaflet.css';` здесь и удали `link` из `index.html`

2020-10-21 07:16 UTC, AKolodeev commented on src/components/leaflet-map/leaflet-map.jsx
> +    .marker(offerCords, this.icon)
Ты передаешь вторым аргументом икноку, тогда как нужно передавать объект со свойством `icon`.
Запись `{icon}` равно записи `{icon: icon}`, но в твоем случае нужно передавать `{icon: this.icon}`.

2020-10-21 07:18 UTC, AKolodeev commented
По поводу `react-leaflet` - мы все правильно сделали, лучше использовать просто `leaflet`, чтобы к нам было меньше вопросов во время ревью другим наставником.

2020-10-21 08:36 UTC, Cestrus commented
Приветствую, Александр! Прошу прощения за как оказалось не рабочий проект,
но я думал, что все работает, т.к. и карта и метки выводились. Впредь буду
проверять тщательнее.

ср, 21 окт. 2020 г. в 10:18, Alexander Kolodeev <notifications@github.com>:

> По поводу react-leaflet - мы все правильно сделали, лучше использовать
> просто leaflet, чтобы к нам было меньше вопросов во время ревью другим
> наставником.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-react/1618361-six-cities-5/pull/9#issuecomment-713363888>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK5NPNORZPO4GA7CUGGEM7TSL2DMTANCNFSM4STQHTKA>
> .
>

2020-10-21 10:35 UTC, Cestrus commented
Большое спасибо за наводку на file-loader. Несколько дней ломал голову почему не работает импорт css в js-файле (оттого в index.html стили и подключил). Проект проверил линтом, запускал npm run start,  cделал bild. Ошибок не было.

2020-10-22 15:36 UTC, AKolodeev commented
> Большое спасибо за наводку на file-loader. Несколько дней ломал голову почему не работает импорт css в js-файле (оттого в index.html стили и подключил). Проект проверил линтом, запускал npm run start, cделал bild. Ошибок не было.

Пожалуйста :) Пиши, не стесняйся, я здесь для того, чтобы отвечать на вопросы и помогать :)

2020-10-22 15:38 UTC, AKolodeev reviewed
Теперь все ОК :) Если есть какие-нибудь вопросы - напиши в телеграм или давай созвонимся :)

2020-10-22 15:38 UTC, merged